### ISSUE TITLE
Add ability to pass executionRoleArn

### ISSUE THREAD

**Issue by bwieckow** [aws-actions/amazon-ecs-render-task-definition#77] opened 2020-12-01 14:51 UTC
When using secrets it is required to add this field. In ARN there are sensitive data like region and AWS account number. Please consider adding this feature.

`Unexpected input(s) 'executionRoleArn', valid inputs are ['task-definition', 'container-name', 'image']`

**Comment by allisaurus** [comment] 2020-12-07 22:23
@bwieckow for either the ECS task role or task execution role, you can specify just the name of the role vs. the full ARN. See: https://github.com/aws-actions/amazon-ecs-render-task-definition/issues/19

**Comment by allisaurus** [comment] 2020-12-11 23:13
Closing as a duplicate of https://github.com/aws-actions/amazon-ecs-render-task-definition/issues/19 , but feel free to reopen if issues remain.

**Closed by allisaurus** 2020-12-11 23:13 UTC
Labels: guidance

**Comment by avaz** [comment] 2022-03-22 05:06
Hi,

I think the goal of this task and even #19 was to be able to dynamic change the task `executionRoleArn` and `taskRoleArn` from this action. This is helpful when one wants to use different roles per environment in a ECS deployment and not only have the account id automatically fulfilled. 

Any chance to reopen this?
